FROM continuumio/miniconda3:latest

WORKDIR /app

# Update pip
RUN pip install -U pip

# Install MLflow requirements
COPY ./pipeline/mlflow/requirements.txt ./mlflow-requirements.txt
RUN pip install -r mlflow-requirements.txt

# Copy over the MLflow project
COPY ./pipeline/mlflow .

USER root
COPY --chown=0 --chmod=777 ./setup.py ./README.md ./
COPY --chown=0 --chmod=777 ./src ./src
COPY --chown=0 --chmod=777 ./artifacts ./artifacts
RUN python ./setup.py install
